// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-2",
  "aws_cognito_identity_pool_id": "us-east-2:9d117b7e-2ad8-4775-97dd-55e3f8394115",
  "aws_cognito_region": "us-east-2",
  "aws_user_pools_id": "us-east-2_dwdFsN50I",
  "aws_user_pools_web_client_id": "7f8at62v2aeqdr6njp7du7me9v",
  "oauth": {},
  "predictions": {
      "interpret": {
          "interpretText": {
              "region": "us-east-2",
              "proxy": false,
              "defaults": {
                  "type": "ALL"
              }
          }
      }
  }
};


export default awsmobile;
